const number1 = 22;
const number2 = 33;
const product = number1 * number2;
console.log('Value of product => ', product, 'Type of product =>', typeof product);
const charge = 4;
const payment = 2;
const amountRemaining = charge - payment;
console.log('Value of amountRemaining => ', amountRemaining, 'typeof amountRemaining =>', typeof amountRemaining);
const tests = 5;
const assignments = 10;
const final = 15;
const grade = (tests + assignments + final) / 3;
console.log('Value of grade => ', grade, 'Type of grade => ', typeof grade);
const firstName = ' Kasiet';
const lastName = 'Rakhimdinova';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName =>', fullName, 'Typeof fullName=>', typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('Value of is Asidic =>', isAcidic, 'Typeof isAcidic =>', typeof isAcidic);
const numberOfSoldiers = 259;
const isSparta = numberOfSoldiers === 300;
console.log('Value of is Sparta =>', isSparta, 'Type ofis Sparta =>', typeof isSparta);
let nickName = fullName;
nickName += nickName + ' is Software Developer';
console.log('Value of nickName => ', nickName, 'Typeof nickName =>', typeof nickName);
